### ISSUE TITLE
（备忘）暗色主题功能

### ISSUE THREAD

**Issue by goldimax** [syzoj/syzoj#58]
其实也可以用如stylish之类的用户CSS搞个第三方的

**Comment by interestingLSY** [comment]
```css
h1,h2,h3,h4,h5,h6,body,th,td,table,label,div.column,p{
    color: #fff !important;
}
code{
    color: #ccc !important;
}
body{
    background-color: #2d2d2d;
}
.ui.header.top, div.pagination, div.selection, input,div.message{
    background-color: #454545 !important;
    color: #fff !important
}
.ui.segment, .ui.table, tbody, thead, td, th,p{
    background-color: #44444400 !important;
    color: #fff !important;
}
.ui.footer{
    background-color: #2d2d2d !important;
}
a{
    color: #66ccff;
}
a.item{
    color: #000 !important;
}
a.black-link{
    color: #fff !important;
}
div.accordion{
    background-color: #44444400 !important;
}
```

可以试试（我随手写的）

**Comment by interestingLSY** [comment]
就是 Editor 里面还是白色，代码高亮不太漂亮

**Comment by interestingLSY** [comment]
解决了上面的问题：

```css
h1,h2,h3,h4,h5,h6,body,th,td,table,label,div.column,p{
    color: #fff !important;
}
code{
    color: #ccc !important;
}
body{
    background-color: #2d2d2d;
}
.ui.header.top, div.pagination, div.selection, input,div.message{
    background-color: #454545 !important;
    color: #fff !important
}
.ui.segment, .ui.table, tbody, thead, td, th,p{
    background-color: #44444400 !important;
    color: #fff !important;
}
.ui.footer{
    background-color: #2d2d2d !important;
}
a{
    color: #66ccff;
}
a.item{
    color: #000 !important;
}
a.black-link{
    color: #fff !important;
}
div.accordion{
    background-color: #44444400 !important;
}

.pl-p, .pl-n{
    color: #bbb !important;
}
#editor, #languages-menu, div.ace_gutter{
    background-color: #333 !important;
}
#languages-menu>a, div.ace_gutter{
    color: #eee !important;
}
div.ace_active-line, div.ace_gutter-active-line, div.ace_selection{
    background-color: #444 !important;
}
span.ace_paren, span.ace_identifier{
    color: #eee !important;
}
span.ace_operator{
     color: #aaa !important;
}
```
