### ISSUE TITLE
功能请求：暗色主题 ( 有附加 css 实现 ）

### ISSUE THREAD

**Issue by interestingLSY** [syzoj/syzoj#99]
如题，希望增加暗色主题功能，并能让用户在亮色与暗色中自由切换

纯手撸的辣鸡 css：

```css
div.ui.fixed.borderless.menu, div.ui.fixed.borderless.menu a{
    background-color: #111 !important;
    color: #fff !important;
}

h1,h2,h3,h4,h5,h6,body,th,td,table,label,div.column,p{
    color: #fff !important;
}
code{
    color: #ccc !important;
}
body{
    background-color: #2d2d2d;
}
.ui.header.top, div.pagination, div.selection, input,div.message{
    background-color: #454545 !important;
    color: #fff !important
}
.ui.segment, .ui.table, tbody, thead, td, th, p{
    background-color: #44444400 !important;
    color: #fff !important;
}
.ui.footer{
    background-color: #2d2d2d !important;
}
a{
    color: #66ccff;
}
a.item{
    color: #000 !important;
}
a.black-link{
    color: #fff !important;
}
div.accordion{
    background-color: #44444400 !important;
}

.pl-p, .pl-n{
    color: #bbb !important;
}
#editor, #languages-menu, div.ace_gutter{
    background-color: #333 !important;
}
#languages-menu>a, div.ace_gutter{
    color: #eee !important;
}
div.ace_active-line, div.ace_gutter-active-line, div.ace_selection{
    background-color: #444 !important;
}
span.ace_paren, span.ace_identifier{
    color: #eee !important;
}
span.ace_operator{
     color: #aaa !important;
}

span.status.accepted, span.score.score_10{
    color: #00d000 !important;
}
```
